//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTbl
    {
        public string AccID { get; set; }
        public string AccEmail { get; set; }
        public string AccName { get; set; }
        public string AccToken { get; set; }
    }
}
