//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagesTbl
    {
        public string PageID { get; set; }
        public string PageToken { get; set; }
        public string PageName { get; set; }
        public Nullable<long> fans { get; set; }
        public string ParentAccountID { get; set; }
    }
}
